### ISSUE TITLE
CGI Won't Run on Ubuntu Server

### ISSUE THREAD

**Issue by RevStrangeHope** [movabletype/movabletype#120]
Every time I try to run the CGI to install the site it just loads up the file but never runs it, I have tried to install it four different times.

not sure if this is on Ubuntu's side or not. some help would be nice

**Comment by dphillips** [comment]
- Check that the mt.cgi script has 755 permissions.
- Check the Apache server configuration to see if .cgi scripts can run from the directory where Movable Type is installed.
- Try browsing to (running) the mt-check.cgi script and see if it runs.

**Comment by RevStrangeHope** [comment]
Have tried all that still having same issue, will reinstall Ubuntu Server 16.04.3 LTS [64-bit] and try again.

**Comment by charsbar** [comment]
Closing.
