### ISSUE TITLE
DataAPI responses can't be cached

### ISSUE THREAD

**Issue by nakedsushi** [movabletype/movabletype#386]
https://github.com/movabletype/movabletype/blob/8989bb7fde91003f7aa36c1467213c9f7b7cac23/lib/MT/App/DataAPI.pm#L2970

I'm using Varnish as a reverse-proxy and would like to cache API responses, but can't because of this `Cache-Control: no-cache` setting.  Is there a reason why the DataAPI is forcing no cache?

Should I do a PR so that this is controlled by an app config like `$app->config->HeaderCacheControl` or get rid of completely?

**Comment by miniuchi** [comment]
@nakedsushi 

This is not right way and we cannot guarantee it at all, but Cache-Control header seems to enable to be changed by post_run callback.

This is a sample plugin.
https://gist.github.com/miniuchi/2a316062196e375e48191fa3706fd2c7

I’m happy if this can solve your problem.

**Comment by nakedsushi** [comment]
@miniuchi Thanks that was a great workaround. I put the plugin here (https://github.com/SCPR/mt-data-api-cache-control-override) and will use it till the next version that has the new config directive.
