### ISSUE TITLE
GPL version

### ISSUE THREAD

**Issue by darkmorpher** [movabletype/movabletype#43]
Where to get the previous open sourced version under GPL?

**Comment by rinopo** [comment]
My understanding is that MTOS (GPL version of MT) isn't officially maintained any more. 😞 
[MovableType.org – News: License change on Movable Type 6](https://movabletype.org/news/2013/07/license_change_on_movable_type_6.html)
[MovableType.org – Product Life Cycle Policy](https://movabletype.org/product-life-cycle-policy.html)
You should beware of possible unpatched security issues if you use it.

That said, you could checkout one of the 5.x branches:
e.g. https://github.com/movabletype/movabletype/tree/support-5.2x

See here on how to do it. https://movabletype.org/news/2011/01/movable_type_development_moving_to_github.html
*Do `git checkout -b support-5.2x` etc., before `make me`.

Or just download the latest veresion from here:
https://movabletype.org/downloads/stable/
