### ISSUE TITLE
Has to Reset Password to Login

### ISSUE THREAD

**Issue by leomoon** [movabletype/movabletype#53]
I upgraded to 6.3.6 and now every time I login, I have to reset password. I've even set the password using mySQL:
update mt_author set author_password = encrypt('YOURPASSWORD') where author_id = 1;

and it still doesn't work.

**Comment by leomoon** [comment]
I figured out why. The user is case sensitive now.

**Comment by dphillips** [comment]
Username is case sensitive as of Movable Type 6.3.5.
