### ISSUE TITLE
Sites and Entries under the menu won't show any items

### ISSUE THREAD

**Issue by imyaman** [movabletype/movabletype#896]
Sites and Entries under the menu won't show any items when CGIPath and StaticWebPath domain names are different in mt7.
After I moved CGI into the site, the items are shown. This has allowed me to see the list temporarily.

CGIPath domain name : mt7.youre.space
StaticWebPath domain name : newlog.youre.space

![mt7-001](https://user-images.githubusercontent.com/1654540/53734503-86a6c080-3ec7-11e9-8b0b-18e95d229d2a.png)

![mt7-002](https://user-images.githubusercontent.com/1654540/53734523-90302880-3ec7-11e9-9b50-205362e10981.png)

**Comment by miniuchi** [comment]
@imyaman 

It looks a problem related to "Access-Control-Allow-Origin" header and "Content-Type" header of your web server.

Please check following links, and documentation for your web browser.

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

**Comment by charsbar** [comment]
Closing.
